name: Scheduled Script Run

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Set environment variables using GitHub secrets
      - name: Set environment variables
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
        run: echo "Environment variables set"

      # Run the Jupyter notebook
      - name: Run notebook
        env:
          APP_KEY: ${{ secrets.APP_KEY }}  # Set it again for the notebook run if required
        run: |
          papermill Fitlist.ipynb Fitlist_output.ipynb
